name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Publish
        run: |
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
